[build]
  command = "next build && next export"
  publish = "out"
  functions = ".netlify/functions"

[[redirects]]
from = "/blog/"
to = "/"

[[redirects]]
from = "/news/"
to = "/"

[[redirects]]
from = "/news/tidal-fluid-power/"
to = "/"
